#!/bin/sh
# statamphup will prepare and submit a Stata-MP job

usage()
{
	echo ""
	echo "The 'statamphup' script submits Stata-MP batch jobs using nohup"
	echo ""
	echo "usage is:"
	echo "	statahup <stata_do_file.do>"
	echo ""
	echo "Please note that spaces in the filename or directory may cause "
	echo "this script to fail."
	echo ""
}

if [ "$#" -eq 1 ]; then
	if [ -r $1 ]; then
		# Tempfile(s) for the script
		tempy=tempy$$
		touch $HOME/bin/$tempy.sh
		shell=$HOME/bin/$tempy.sh
		chmod +x $shell

		echo '#!/bin/sh' > $shell
		echo "stata-mp -b do $1 " >> $shell
		nohup $shell &
		# Nohup takes a split second longer than other commands
		sleep .5s

		# Delete the tempfile
		rm -f $shell
	else
		echo ""
		echo "File does not exist"
		echo ""
	fi
else
	usage
fi

